name: Deploy to Raspberry Pi

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker buildx build --platform linux/arm64 -t yourusername/yourapp:latest --push .

    - name: SSH and deploy
      uses: appleboy/ssh-action@v0.1.2
      with:
        host: ${{ secrets.RPI_HOST }}
        username: ${{ secrets.RPI_USER }}
        key: ${{ secrets.RPI_KEY }}
        script: |
          docker pull yourusername/yourapp:latest
          docker-compose -f /path/to/your/docker-compose.yml up -d
