name: Deploy to Raspberry Pi

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker buildx build --platform linux/arm64 -t zsanger/dreaminsight:latest --push .

    - name: SSH and deploy
      uses: appleboy/ssh-action@v0.1.2
      with:
        host: ${{ secrets.PI_HOST }}
        port: 22
        username: sange
        password: ${{ secrets.SSH_PASSWORD }}
        script: |
          echo ${{ secrets.SSH_PASSWORD }} | sudo -S docker pull zsanger/dreaminsight:latest
          echo ${{ secrets.SSH_PASSWORD }} | sudo -S docker-compose -f /home/sange/DreamInsight/docker-compose.yml up -d
